//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineHistory
    {
        public int MachineHistoryID { get; set; }
        public int MachineID { get; set; }
        public int MachineStatusID { get; set; }
        public string Description { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<System.DateTime> NextReminderOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual MachineMaster MachineMaster { get; set; }
        public virtual MachineStatusMaster MachineStatusMaster { get; set; }
    }
}
