//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailMaster
    {
        public int MailID { get; set; }
        public string To { get; set; }
        public string From { get; set; }
        public string CC { get; set; }
        public string BCC { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string Attachments { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreationTimestamp { get; set; }
        public Nullable<System.DateTime> SentTimestamp { get; set; }
        public string Exception { get; set; }
        public byte[] AttachementsBytes { get; set; }
        public string AttachementFileNameWithExtension { get; set; }
    }
}
