//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MouldHistory
    {
        public int MouldIHistoryID { get; set; }
        public int MouldID { get; set; }
        public int MouldStatusID { get; set; }
        public string Description { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<System.DateTime> NextReminderOn { get; set; }
    
        public virtual MouldMaster MouldMaster { get; set; }
        public virtual MouldStatusMaster MouldStatusMaster { get; set; }
    }
}
