//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationLog
    {
        public int SmsId { get; set; }
        public int DispatchId { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string MessageText { get; set; }
        public Nullable<System.DateTime> SentAt { get; set; }
        public string SmsStatus { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> Updatedy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
