//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductGroupDetail
    {
        public int ProductGroupDetailsID { get; set; }
        public int ProductGroupID { get; set; }
        public int ProductID { get; set; }
        public int Qty { get; set; }
        public bool IsDiscontinued { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual ProductGroupMaster ProductGroupMaster { get; set; }
        public virtual ProductMaster ProductMaster { get; set; }
    }
}
