//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRawMaterialMapping
    {
        public int ProductRMMappingID { get; set; }
        public int ProductID { get; set; }
        public int RawMaterialID { get; set; }
        public int RMReqdForUOMQty { get; set; }
        public byte UnitType { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> RMGradeUsed { get; set; }
    
        public virtual ProductMaster ProductMaster { get; set; }
        public virtual RawMaterialMaster RawMaterialMaster { get; set; }
    }
}
