//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionProgram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionProgram()
        {
            this.ProdReadyStoreds = new HashSet<ProdReadyStored>();
            this.ProductionProgramBatches = new HashSet<ProductionProgramBatch>();
            this.ProductionProgramRMMappings = new HashSet<ProductionProgramRMMapping>();
            this.ProductionRawMaterials = new HashSet<ProductionRawMaterial>();
        }
    
        public int ProductionProgramID { get; set; }
        public Nullable<int> SalesDetailsID { get; set; }
        public int ProductID { get; set; }
        public int ProductQty { get; set; }
        public int MouldID { get; set; }
        public Nullable<int> MachineID { get; set; }
        public int InProductionQty { get; set; }
        public int ProductQtyCompleted { get; set; }
        public int UserID { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual MachineMaster MachineMaster { get; set; }
        public virtual MouldMaster MouldMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdReadyStored> ProdReadyStoreds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionProgramBatch> ProductionProgramBatches { get; set; }
        public virtual SalesDetail SalesDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionProgramRMMapping> ProductionProgramRMMappings { get; set; }
        public virtual ProductMaster ProductMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionRawMaterial> ProductionRawMaterials { get; set; }
    }
}
