//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductMaster()
        {
            this.ProdReadyStoreds = new HashSet<ProdReadyStored>();
            this.ProductGroupDetails = new HashSet<ProductGroupDetail>();
            this.ProductInventoryMasters = new HashSet<ProductInventoryMaster>();
            this.ProductionPrograms = new HashSet<ProductionProgram>();
            this.ProductRawMaterialMappings = new HashSet<ProductRawMaterialMapping>();
            this.SalesDetails = new HashSet<SalesDetail>();
            this.SalesDispatchDetails = new HashSet<SalesDispatchDetail>();
            this.SalesDispatchRacks = new HashSet<SalesDispatchRack>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public string Description { get; set; }
        public int ProductCategoryID { get; set; }
        public int UOMID { get; set; }
        public decimal MinQtyUOM { get; set; }
        public int ConversionUOMID { get; set; }
        public decimal ConversionQty { get; set; }
        public int MouldID { get; set; }
        public Nullable<int> PkgQty { get; set; }
        public Nullable<int> PkgsPerRack { get; set; }
        public bool IsDiscontinued { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public decimal MaximumSellingPrice { get; set; }
        public string Colour { get; set; }
        public decimal MinimumSellingPrice { get; set; }
    
        public virtual MouldMaster MouldMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdReadyStored> ProdReadyStoreds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductGroupDetail> ProductGroupDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInventoryMaster> ProductInventoryMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionProgram> ProductionPrograms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductRawMaterialMapping> ProductRawMaterialMappings { get; set; }
        public virtual UOMMaster UOMMaster { get; set; }
        public virtual UOMMaster UOMMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesDetail> SalesDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesDispatchDetail> SalesDispatchDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesDispatchRack> SalesDispatchRacks { get; set; }
    }
}
