//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionRawMaterial
    {
        public int ProductionRMID { get; set; }
        public int ProductionProgramID { get; set; }
        public int RawMaterialID { get; set; }
        public int RMInventoryID { get; set; }
        public int RMQty { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual ProductionProgram ProductionProgram { get; set; }
        public virtual RawMaterialInventoryMaster RawMaterialInventoryMaster { get; set; }
        public virtual RawMaterialMaster RawMaterialMaster { get; set; }
    }
}
