//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseDetail()
        {
            this.PurchaseRcvdDetails = new HashSet<PurchaseRcvdDetail>();
        }
    
        public int PurchaseDetailsID { get; set; }
        public int PurchaseID { get; set; }
        public int RawMatarialID { get; set; }
        public int Qty { get; set; }
        public string Instructions { get; set; }
        public int RcvdQty { get; set; }
        public string ItemType { get; set; }
        public string RMGrade { get; set; }
    
        public virtual PurchaseMaster PurchaseMaster { get; set; }
        public virtual RawMaterialMaster RawMaterialMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseRcvdDetail> PurchaseRcvdDetails { get; set; }
    }
}
