//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseMaster()
        {
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
            this.PurchaseRcvdMasters = new HashSet<PurchaseRcvdMaster>();
        }
    
        public int PurchaseID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int CompanyLocationID { get; set; }
        public string Instructions { get; set; }
        public int PurchaseStatusID { get; set; }
        public int UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual PurchaseStatusMaster PurchaseStatusMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseRcvdMaster> PurchaseRcvdMasters { get; set; }
    }
}
