//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRcvdStored
    {
        public int PurRcvdStoredID { get; set; }
        public int PurchaseRcvdDetailsID { get; set; }
        public int Qty { get; set; }
        public int PalletID { get; set; }
        public int TagColourID { get; set; }
        public Nullable<int> RawMaterialID { get; set; }
        public Nullable<System.DateTime> RcvdDate { get; set; }
    
        public virtual PalletMaster PalletMaster { get; set; }
        public virtual PurchaseRcvdDetail PurchaseRcvdDetail { get; set; }
        public virtual RawMaterialMaster RawMaterialMaster { get; set; }
        public virtual TagColourMaster TagColourMaster { get; set; }
    }
}
