//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialInventoryMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RawMaterialInventoryMaster()
        {
            this.ProductionRawMaterials = new HashSet<ProductionRawMaterial>();
        }
    
        public int RMInventoryID { get; set; }
        public int PalletID { get; set; }
        public int RawMaterialID { get; set; }
        public int TagColourID { get; set; }
        public decimal Qty { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> MinOrderlevel { get; set; }
    
        public virtual PalletMaster PalletMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionRawMaterial> ProductionRawMaterials { get; set; }
        public virtual RawMaterialMaster RawMaterialMaster { get; set; }
        public virtual TagColourMaster TagColourMaster { get; set; }
    }
}
