//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RawMaterialMaster()
        {
            this.ProductionProgramRMMappings = new HashSet<ProductionProgramRMMapping>();
            this.ProductionRawMaterials = new HashSet<ProductionRawMaterial>();
            this.ProductRawMaterialMappings = new HashSet<ProductRawMaterialMapping>();
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
            this.PurchaseRcvdStoreds = new HashSet<PurchaseRcvdStored>();
            this.RawMaterialInventoryMasters = new HashSet<RawMaterialInventoryMaster>();
        }
    
        public int RawMaterialID { get; set; }
        public string RawMaterialName { get; set; }
        public string Description { get; set; }
        public int UOMID { get; set; }
        public bool IsDiscontinued { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionProgramRMMapping> ProductionProgramRMMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionRawMaterial> ProductionRawMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductRawMaterialMapping> ProductRawMaterialMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseRcvdStored> PurchaseRcvdStoreds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RawMaterialInventoryMaster> RawMaterialInventoryMasters { get; set; }
        public virtual UOMMaster UOMMaster { get; set; }
    }
}
