//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDispatchDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesDispatchDetail()
        {
            this.SalesDispatchRacks = new HashSet<SalesDispatchRack>();
        }
    
        public int SalesDispatchID { get; set; }
        public int SalesDetailsID { get; set; }
        public int ProductID { get; set; }
        public int DispatchQty { get; set; }
        public int UserID { get; set; }
        public System.DateTime DispatchDate { get; set; }
        public string DispatchNotes { get; set; }
        public Nullable<decimal> TransporterCharges { get; set; }
        public string Transporter { get; set; }
        public string DocketNo { get; set; }
        public string DispatchStatus { get; set; }
        public string DocketPhotoPath { get; set; }
        public Nullable<bool> SmsSentFlag { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<decimal> TransportationCharge { get; set; }
    
        public virtual ProductMaster ProductMaster { get; set; }
        public virtual SalesDetail SalesDetail { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesDispatchRack> SalesDispatchRacks { get; set; }
    }
}
