//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesDetail()
        {
            this.ProductionPrograms = new HashSet<ProductionProgram>();
            this.SalesDispatchDetails = new HashSet<SalesDispatchDetail>();
        }
    
        public int SalesDetailsID { get; set; }
        public int SalesID { get; set; }
        public int ProductID { get; set; }
        public int Qty { get; set; }
        public string Instructions { get; set; }
        public int QtyBlocked { get; set; }
        public int QtyRMBlocked { get; set; }
        public int QtyInProduction { get; set; }
        public int QtyProduced { get; set; }
        public int QtyToDispatch { get; set; }
        public int QtyDispatched { get; set; }
        public int QtyBal { get; set; }
        public int SalesStatusID { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionProgram> ProductionPrograms { get; set; }
        public virtual ProductMaster ProductMaster { get; set; }
        public virtual SalesMaster SalesMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesDispatchDetail> SalesDispatchDetails { get; set; }
    }
}
