//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDispatchTransporterDetail
    {
        public int SDTRDId { get; set; }
        public string Transporter { get; set; }
        public Nullable<decimal> TransportationCharge { get; set; }
        public string DocketNo { get; set; }
        public string DispatchStatus { get; set; }
        public string DocketPhotoPath { get; set; }
        public string BillNo { get; set; }
        public string PackedBy { get; set; }
        public bool SmsSentFlag { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> SalesDetailsID { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
    }
}
