//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDispatchRack
    {
        public int SalesDispatchRackID { get; set; }
        public int SalesDispatchID { get; set; }
        public int ProductID { get; set; }
        public int RackID { get; set; }
        public int Qty { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual ProductMaster ProductMaster { get; set; }
        public virtual RackMaster RackMaster { get; set; }
        public virtual SalesDispatchDetail SalesDispatchDetail { get; set; }
    }
}
