//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesMaster()
        {
            this.SalesDetails = new HashSet<SalesDetail>();
        }
    
        public int SalesID { get; set; }
        public System.DateTime SalesDate { get; set; }
        public int CompanyLocationID { get; set; }
        public string Instructions { get; set; }
        public int SalesStatusID { get; set; }
        public int UserID { get; set; }
        public string Notes { get; set; }
        public string PONo { get; set; }
        public string Colour { get; set; }
        public string GMS { get; set; }
        public string GMSInfo { get; set; }
        public string Package { get; set; }
        public string Quantity { get; set; }
        public bool SampleRequired { get; set; }
        public string DeliveryAddress { get; set; }
        public string Transporter { get; set; }
        public Nullable<System.DateTime> CommittedDate { get; set; }
        public string Rate { get; set; }
        public string PaymentStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesDetail> SalesDetails { get; set; }
        public virtual SalesStatusMaster SalesStatusMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
