//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagColourMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TagColourMaster()
        {
            this.PurchaseRcvdStoreds = new HashSet<PurchaseRcvdStored>();
            this.RawMaterialInventoryMasters = new HashSet<RawMaterialInventoryMaster>();
        }
    
        public int TagColourID { get; set; }
        public string TagColour { get; set; }
        public bool IsDiscontinued { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseRcvdStored> PurchaseRcvdStoreds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RawMaterialInventoryMaster> RawMaterialInventoryMasters { get; set; }
    }
}
