//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPIWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorMaster
    {
        public int VendorId { get; set; }
        public string VendorName { get; set; }
        public string Notes { get; set; }
        public string Address { get; set; }
        public Nullable<int> ContactNumber { get; set; }
        public bool IsDiscontinued { get; set; }
        public int AddedBy { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    }
}
